name: test workflow outputs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.txt' 
      
concurrency: 
      group: ${{ github.workflow }}
      cancel-in-progress: false
      
jobs:
  update_token:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - run: |
          echo 'github.workflow = ${{ github.workflow }}';
          echo 'github.event.workflow = ${{ github.event.workflow }}';
          echo 'github.event.workflow_run.conclusion = ${{ github.event.workflow_run.conclusion }}';
          echo 'github.event_name = ${{ github.event_name }}';
