name: Updating window.crypto.subtle keys on a schedule

on:
  push:
    branches:
      - main
      
jobs:
  update_token:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Open webpage to run Frontend process
        run: python -m webbrowser "https://codesolutions2.github.io/frontend_backend_message_passing_central_repository_v1/index_reset.html"
        
