name: Updating window.crypto.subtle keys on a schedule

on:
  push:
    branches:
      - main
      
jobs:
  update_token:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m webbrowser -n "https://codesolutions2.github.io/frontend_backend_message_passing_central_repository_v1/index_reset.html"
